
import "@/styles/globals.css"

export const metadata = {
  title: "Next Starter Template",
  description: 'Generated by Next.js',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,1,0" />
      </head>
      <body>{children}</body>
    </html>
  )
}
